[#include "/gato-template/templates/includes/commonmacros.ftl"]
[#include "/gato-component-patterns/templates/includes/pattern.ftl"]
[@prebuiltsection]
  [#assign mobileImage = getMobileImage(content.image, content.mobileImage!)]
  [#if cmsfn.isEditMode()]<div cms:edit></div>[/#if]
    [@cms.area name="tabs" contextAttributes={"overlayPosition": content.overlayPosition, "overlayColor": content.color, "desktopImage": content.image, "mobileImage": mobileImage}/]
[/@prebuiltsection]