[#macro sociallinks parentnode='' icononly=false]
  [#if parentnode?has_content && gf.hasChildren(parentnode)]
    <ul class="social-media-icons">
      [#list cmsfn.children(parentnode) as socialink]
        [#if socialink.link?has_content]
          [#assign slink = socialink.link?lower_case]
          [#if slink?contains("facebook")]
            [#assign iconclass="fa-facebook-square"]
            [#assign alttext="Facebook"]
          [#elseif slink?contains("flickr")]
            [#assign iconclass="fa-flickr"]
            [#assign alttext="Flickr"]
          [#elseif slink?contains("github")]
            [#assign iconclass="fa-github"]
            [#assign alttext="Github"]
          [#elseif slink?contains("instagram")]
            [#assign iconclass="fa-instagram"]
            [#assign alttext="Instagram"]
          [#elseif slink?contains("linkedin")]
            [#assign iconclass="fa-linkedin-square"]
            [#assign alttext="LinkedIn"]
          [#elseif slink?contains("pinterest")]
            [#assign iconclass="fa-pinterest-square"]
            [#assign alttext="Pinterest"]
          [#elseif slink?contains("snapchat")]
            [#assign iconclass="fa-snapchat-square"]
            [#assign alttext="Snapchat"]
          [#elseif slink?contains("spotify")]
            [#assign iconclass="fa-spotify"]
            [#assign alttext="Spotify"]
          [#elseif slink?contains("tumblr")]
            [#assign iconclass="fa-tumblr-square"]
            [#assign alttext="Tumblr"]
          [#elseif slink?contains("twitter")]
            [#assign iconclass="fa-twitter-square"]
            [#assign alttext="Twitter"]
          [#elseif slink?contains("vimeo")]
            [#assign iconclass="fa-vimeo-square"]
            [#assign alttext="Vimeo"]
          [#elseif slink?contains("wordpress")]
            [#assign iconclass="fa-rss-square"]
            [#assign alttext="Wordpress"]
          [#elseif slink?contains("txstate.edu")]
            [#assign iconclass="fa-star"]
            [#assign alttext="Texas State"]
          [#elseif slink?matches(r".*youtu\.?be.*")]
            [#assign iconclass="fa-youtube-square"]
            [#assign alttext="YouTube"]
          [#elseif slink?contains("plus.google")]
            [#assign iconclass="fa-google-plus-square"]
            [#assign alttext="Google Plus"]
          [/#if]

          [#if !alttext?has_content]
          [#-- unrecognized service, let's see if we can regex out the top two levels of their domain name --]
          [#assign alttext = socialink.link?replace('^.*//','','r')?replace('/.*', '', 'r')?replace('^[^\\.]*\\.([^\\.]*\\.[^\\.]*)$','$1','r')]
          [#if !alttext?has_content][#assign alttext = "Social Link"][/#if]
          [/#if]

          [#assign linktext = socialink.title!alttext]
          [#if icononly]
            [#assign linktextclass = 'visuallyhidden']
          [#else]
            [#assign linktextclass = '']
          [/#if]

          [#assign title = alttext]
          [#if linktext?lower_case?contains(alttext?lower_case)]
          [#assign title = '']
          [/#if]
          [#if !iconclass?has_content]
            [#assign iconclass = 'fa-share-alt-square']
          [/#if]
          <li>
            <a href="${gf.filterUrl(socialink.link)}" class="gato-sociallink ${(ctx.icononly!false)?string('icononly','')}">
               [#if socialink.icon?has_content]
                 <img src="${damfn.getAssetLink(socialink.icon)!}" alt="${title}"/>[#--
               --][#else][#--
                 --]<i class="fa ${iconclass}" [#if title?has_content]aria-label="${title}"[#else]aria-hidden="true"[/#if]></i>[#--
               --][/#if][#--
               --]<span class="${linktextclass}">${linktext}</span>[#--
             --]</a>
          </li>
        [/#if]
        [#assign iconclass=""]
        [#assign alttext=""]
      [/#list]
    </ul>
  [#elseif cmsfn.isEditMode()]
    <div cms:edit="bar"></div>
    <div class="gato-editor-warning">Social media links were left empty!</div>
  [/#if]
[/#macro]
