
<jsp:root version="2.0" xmlns:jsp="http://java.sun.com/JSP/Page">

<jsp:directive.page contentType="text/html; charset=UTF-8" session="false"/>
<jsp:output doctype-root-element="html"
	doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
	doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" />
<jsp:directive.page import="info.magnolia.importexport.DataTransporter" />
<jsp:directive.page import="info.magnolia.repository.RepositoryConstants" />
<jsp:directive.page import="info.magnolia.context.MgnlContext" />
<jsp:directive.page import="java.util.Iterator" />
<jsp:directive.page import="java.io.File" />
<jsp:directive.page import="java.io.IOException" />
<jsp:directive.page import="org.apache.commons.lang.StringUtils" />
<jsp:directive.page import="java.util.Arrays" />

<html>
	<head>
		<title>Import files generated by backup-page.jsp</title>
	</head>
	<body>

<jsp:declaration><![CDATA[
	public File fileFromPath (String path, String repo, String fs, String timestamp) throws IOException {
		String pathName = StringUtils.replace(path, DataTransporter.SLASH, DataTransporter.DOT);
		pathName = DataTransporter.encodePath(pathName, DataTransporter.DOT, DataTransporter.UTF8);
		if (DataTransporter.DOT.equals(pathName)) {
				// root node
				pathName = StringUtils.EMPTY;
		}
		if (!StringUtils.endsWith(fs, "/")) fs = fs + "/";
		File ret = new File(fs+repo+pathName+".xml"+timestamp);
		return ret;
	}

	public void importPage (JspWriter out, String path, String repo, String fs, String timestamp) throws IOException {
		try {
			String basepath = path.replaceAll("/[^/]+/?$", "/");
			out.print("Restoring "+path+" into "+basepath+" ... ");
			DataTransporter.importFile(
					fileFromPath(path, repo, fs, timestamp),
					repo,
					basepath,
					true,
					2,
					true,
					true);
			out.println("import-succeeded!");
			out.flush();
		} catch (Exception e) {
			out.println("import-failed!");
			e.printStackTrace(new java.io.PrintWriter((java.io.Writer) out));
			e.printStackTrace();
			out.flush();
		}
	}
]]></jsp:declaration>

<jsp:scriptlet><![CDATA[
	String path = request.getParameter("path");
	if (StringUtils.isEmpty(path)) path = "/";
	if (!StringUtils.startsWith(path, "/")) path = "/"+path;

	String repo = request.getParameter("repo");
	if (StringUtils.isEmpty(repo)) repo = RepositoryConstants.WEBSITE;

	String fs = request.getParameter("fs");
	if (StringUtils.isEmpty(fs)) fs = "/var/backup";

	String timestamp = request.getParameter("timestamp");
	if (StringUtils.isEmpty(timestamp)) timestamp = "";
	else if (!StringUtils.startsWith(timestamp, ".")) timestamp = "."+timestamp;

	String[] workspaces = {"config", "dam", "dms", "gatoapps", "usergroups", "userroles", "users", "website"};
	if (Arrays.asList(workspaces).contains(repo)) {
		out.println("Restoring from backup files...<br/>");
		out.println("repository: "+repo+"<br/>");
		out.println("path: "+path+"<br/>");
		out.println("base file path: "+fs+"<br/>");
		out.flush();
		importPage(out, path, repo, fs, timestamp);
	} else {
		out.println("Unknown repo ... import-failed!");
		out.flush();
	}
]]></jsp:scriptlet>

	</body>
</html>
</jsp:root>
