[#include "/gato-template/templates/includes/commonmacros.ftl"]
[#if cmsfn.isEditMode()]<div cms:edit></div>[/#if]
[#if content.title?has_content]
  [@h2 class="level1header image-gallery-title"]${content.title}[/@h2]
[/#if]
[@cms.area name="images"/]
[#include "/gato-lib/templates/includes/pswpmodal.ftl"]
