[#include "/gato-template/templates/includes/commonmacros.ftl"]
[#if cmsfn.isEditMode()]<div cms:edit></div>[/#if]
[#if !gf.isEmptyString(content.title)]
  [@h2 class="image-gallery-title"]${content.title}[/@h2]
[/#if]
[#if content.caption?has_content]
  <p>${content.caption}</p>
[/#if]
[@cms.area name="images"/]
[#include "/gato-lib/templates/includes/pswpmodal.ftl"]
