[#include "/gato-template/templates/includes/component.ftl"]
[#assign mypage = cmsfn.page(content)]
[#assign inheritancelist = [mypage]+cmsfn.ancestors(mypage)?reverse]

[#list inheritancelist as page]
  [#assign himg = gf.singleComponent(page, 'subpage-banner')!]
  [#if himg?has_content]
    [#if himg?has_content && (himg.visible=='hidden' || (himg.visible=='shown' && himg.image?has_content))]
      [#break]
    [/#if]
  [#else]
    [#-- TODO: I'm not sure if the designers want to inherit the banner from the home page --]
    [#assign himg = gf.singleComponent(page, 'home-banner')!]
  [/#if]
[/#list]

[#assign defaultSrc = gf.getImgDefault(himg.image)]

[#assign hasImage = false]
[#if himg?has_content && himg.visible?? && himg.visible == 'shown' && defaultSrc?has_content]
  [#assign hasImage = true]
  [#assign srcset = gf.getSrcSet(himg.image)]
[/#if]
