jQuery( document ).ready(function($) {
  magnolialabelchange('.mainContent_add', '.mgnlEditor.mgnlPlaceholder', 'Add Section');
  magnolialabelchange('.navBlocks_add', '.mgnlEditor.mgnlPlaceholder', 'Add Link Group');
  magnolialabelchange('.socallist_add', '.mgnlEditor.mgnlPlaceholder', 'Add Social Media Links');
  magnolialabelchange('.listItems_add', '.mgnlEditor.mgnlPlaceholder', 'Add Link');
  magnolialabelchange('.txst-gallery-image.add', '.mgnlEditor.mgnlPlaceholder', 'Add Image');
  magnolialabelchange('.feature_add', '.mgnlEditor.mgnlPlaceholder', 'Add Slide');
  magnolialabelchange('.feature_max', '.mgnlEditor.mgnlPlaceholder', 'Maximum slides added');
  magnolialabelchange('.gato-section', '.section-bar>.mgnlEditor.component', 'Section');
  magnolialabelchange('.column_add', '.mgnlEditor.mgnlPlaceholder', 'Add Content');
  magnolialabelchange('.genEmergency_add', '.mgnlEditor.mgnlPlaceholder', 'Add Emergency Information');
  magnolialabelchange('.emergencyHours_add', '.mgnlEditor.mgnlPlaceholder', 'Add Emergency Hours');
  magnolialabelchange('.librarySocial_add', '.mgnlEditor.mgnlPlaceholder', 'Add Social Media Link');
  magnolialabelchange('.link_add', '.mgnlEditor.mgnlPlaceholder', 'Add Link');
  magnolialabelchange('.contactInfo_add', '.mgnlEditor.mgnlPlaceholder', 'Add Contact Information');
  magnolialabelchange('.headerImage_admin', '.mgnlEditor.mgnlPlaceholder', 'Set Banner Image');
  magnolialabelchange('.gato-banners-admin', '.mgnlEditor.mgnlPlaceholder', 'Set Banner Images');
  magnolialabelchange('.slide_add', '.mgnlEditor.mgnlPlaceholder', 'Add Slide');
  magnolialabelchange('.content_add', '.mgnlEditor.mgnlPlaceholder', 'Add Content');
  magnolialabelchange('.imageLink_add', '.mgnlEditor.mgnlPlaceholder', 'Add Image Link');
  magnolialabelchange('#sidebar-paragraphs', '.mgnlEditor.mgnlPlaceholder', 'Add Content');
  magnolialabelchange('.tsus-rightcolumn', '.mgnlEditor.mgnlPlaceholder', 'Add Content');
  magnolialabelchange('.mail_add', '.mgnlEditor.mgnlPlaceholder', 'Add Form Content');
  magnolialabelchange('#gato-customjs-modal', '.mgnlEditor.mgnlPlaceholder', 'Add Custom Javascript');
  magnolialabelchange('#gato-customcss-modal', '.mgnlEditor.mgnlPlaceholder', 'Add Custom CSS');
  magnolialabelchange('.event_add', '.mgnlEditor.mgnlPlaceholder', 'Add Event');
  magnolialabelchange('.parentOrg_add', '.mgnlEditor.mgnlPlaceholder', 'Add Parent Organization');
  magnolialabelchange('.footerLinks_admin', '.mgnlEditor.component', 'Toggle Footer Button');
  magnolialabelchange('.masonry-section', '.mgnlEditor.mgnlPlaceholder', 'Add Card');
  magnolialabelchange('.contact-info .contact-container', '.mgnlEditor.mgnlPlaceholder', 'Contact Information');
  magnolialabelchange('.contact-info .social-media', '.mgnlEditor.mgnlPlaceholder', 'Social Media Links');
  magnolialabelchange('footer .link-footer .top .listItems_add', '.mgnlEditor.mgnlPlaceholder', 'Add Footer Nav Link');
  magnolialabelchange('footer .link-footer .bottom .listItems_add', '.mgnlEditor.mgnlPlaceholder', 'Add Footer Link');
  titledlabelchange('.slider-edit-bar');
});
