[#assign mypage = cmsfn.page(content)]
[#assign inheritancelist = [mypage]+cmsfn.ancestors(mypage)?reverse]
[#list inheritancelist as page]
  [#assign himg = gf.singleComponent(page, 'headerImage')!]
  [#if himg?has_content && (himg.visible=='hidden' || (himg.visible=='shown' && himg.shown?has_content))]
    [#break]
  [/#if]
[/#list]

[#assign defaultSrc = gf.getImgDefault(himg.shown)]
[#assign imgClass = "bg_image_none"]
[#assign headerClass = "header_no_image"]
[#if himg?has_content && himg.visible == 'shown' && defaultSrc?has_content]
	[#assign imgClass = "bg_image"]
	[#assign headerClass = "header_with_image"]
[/#if]
