[#if component??]
  [@cms.component content=component/]
[#else]
  [#list cmsfn.ancestors(cmsfn.page(content))! as ancestor]
    [#assign banner = gf.singleComponent(ancestor, 'gato-banners')]
    [#if banner??]
      [@cms.component content=banner editable=false/]
      [#break]
    [/#if]
  [/#list]
[/#if]
