[#if component??]
  [@cms.component content=component/]
[#else]
  [#list cmsfn.ancestors(cmsfn.page(content))! as ancestor]
    [#assign banner = gf.singleComponent(ancestor, 'gato-banners')!]
    [#if banner?has_content]
      [@cms.component content=banner editable=false /]
      [#break]
    [/#if]
  [/#list]
[/#if]
[#if cmsfn.isEditMode()]<div class="gato-banners-admin" cms:add="bar"></div>[/#if]
