[#function rowHasRTE components]
    [#list components as component]
        [#if cmsfn.metaData(component, "mgnl:template") == "gato-component-patterns:components/textlink"]
            [#return true]
        [/#if]
    [/#list]
    [#return false]
[/#function]
[#function rowHasWide components]
    [#list components as component]
        [#if component.isWide?has_content && component.isWide]
            [#return true]
        [/#if]
    [/#list]
    [#return false]
[/#function]

[#if components?size == 1]
  [#assign orientation = 'full']
[#elseif components?size == 2]
  [#if rowHasRTE(components)]
    [#assign orientation = 'normal']
  [#else]
    [#assign orientation = 'wide']
  [/#if]

  [#if rowHasWide(components)]
    [#if component.isWide?has_content && component.isWide]
      [#assign orientation = 'wide']
    [#else]
      [#assign orientation = 'normal']
    [/#if]
  [/#if]
[#else]
  [#assign orientation = 'normal']
[/#if]
  
  
[#if component.isWide?has_content && component.isWide]
  [#assign orientation = 'wide']
[/#if]
[#if cmsfn.metaData(component, "mgnl:template") == "gato-component-patterns:components/textlink"]
  [#assign type = "text"]
  [#if component.includeImage?? && component.includeImage == "hasImage"]
    [#assign type = type + " " + (component.imageAlignment!"image-left")]
  [/#if]
[#else]
  [#assign type = '']
[/#if]
[#if cmsfn.metaData(component, "mgnl:template") == "gato-component-patterns:components/textlink" || orientation == "wide"]
  [#assign flexGrow = 'flex-grow: 2']
[#elseif orientation == "full"]
  [#assign flexGrow = 'flex-grow: 3']
[#else]
  [#assign flexGrow = 'flex-grow: 1']
[/#if]